### PR TITLE
Bugfix/veto rollback

### LINKED ISSUE #201: Veto rollbacks wrong card
It did delete fascist instead of the almost last one, liberal.
It was almost the last card on the board.

Flow:
fascist, fascist, fascist, fascist, liberal

### PR DESCRIPTION
**Pull request by polarny**
Resolves #201

### CODE REVIEW

File: events/SocketEvents.mjs [hunk 1]
```diff
@@ -79,11 +79,13 @@ import {
 const { isNil, includes, find, get, truncate } = lodash
 
 export const triggerVetoPrompt = (socket) => {
+    console.log("triggerVetoPrompt");
```
Comment (Dammic) [inline events/SocketEvents.mjs]: :scissors:

File: events/SocketEvents.mjs [hunk 2]
```diff
@@ -79,11 +79,13 @@ import {
 const { isNil, includes, find, get, truncate } = lodash
 
 export const triggerVetoPrompt = (socket) => {
+    console.log("triggerVetoPrompt");
     setGamePhase(socket.currentRoom, GamePhases.ServerWaitingForVeto)
 
     const delay = TimeDelay.VETO_DELAY
     
     const notifyAndResume = (delay) => {
+        console.log("notifyAndResume")
```
Comment (Dammic) [inline events/SocketEvents.mjs]: :scissors:

File: events/EnactPolicyEvents.mjs [hunk 3]
```diff
@@ -63,14 +63,15 @@ export const enactPolicyEvent = (socket, policy) => {
...
+    
     const topCard = hasPolicyBeenEnacted ? peekLastEnactedPolicyCard(socket.currentRoom) : null
     const isFacist = topCard === PolicyCards.FacistPolicy
     const activeSuperpowerCallback = isFacist ? checkForImmediateSuperpowers(socket) : null
 
     let nextStepFunction;
     if (activeSuperpowerCallback) {
         nextStepFunction = activeSuperpowerCallback;
-    } else if (checkIfGameShouldFinish(socket.currentRoom)) {
+    } else if (checkIfGameShouldFinish(socket.currentRoom) && !getCustomNextStep) {
```
Comment (Dammic) [inline events/EnactPolicyEvents.mjs]: getCustomNextStep is not related to this at all and should not be part of this if

File: events/emits/superpowers.mjs [hunk 4]
```diff
@@ -27,7 +27,7 @@ export const emitPeekAffiliationToPresident = (room) => {
 
 export const emitServerWaitingForVeto = (room, role) => {
     const roleEmit = getRoleSocket(room, role)
-
+    console.log(emitServerWaitingForVeto);
```
Comment (Dammic) [inline events/emits/superpowers.mjs]: :scissors:

File: src/utils/SocketHandler.js [hunk 5]
```diff
@@ -41,6 +41,7 @@ export class SocketHandler extends React.PureComponent {
             this.switchRooms(roomName)
         })
         socket.on(SocketEvents.ServerWaitingForVeto, (payload) => {
+            console.log("SocketEvents.ServerWaitingForVeto");
```
Comment (Dammic) [inline src/utils/SocketHandler.js]: :scissors:

File: src/utils/SocketHandler.js [hunk 6]
```diff
@@ -201,7 +202,8 @@ export class SocketHandler extends React.PureComponent {
         })
 
         socket.on(SocketEvents.ResetTracker, (payload) => {
-            const trackerPositionBeforeReset = store.room.trackerPosition
+            console.log(this.props)
```
Comment (Dammic) [inline src/utils/SocketHandler.js]: :scissors:

File: utils/RoomsManager/__tests__/voting.test.mjs [hunk 7]
```diff
@@ -105,4 +105,15 @@ describe('voting', () => {
             expect(result).toEqual(['ula', 'iza'])
         })
     })
+
+    describe('getChancellorChoices', () => {
+        test('returns players that did not vote #2', () => {
+            const { testRoom } = roomsStore
+            testRoom.playersDict = {
```
Comment (Dammic) [inline utils/RoomsManager/__tests__/voting.test.mjs]: You will need to update this test to take 'updateRoom' into consideration.
Also, this test doesn't do anything

File: utils/RoomsManager/policies.mjs [hunk 8]
```diff
@@ -42,7 +43,8 @@ export const discardPolicy = (roomName, card) => {
 
 export const discardPolicyByVeto = (roomName) => {
     const { policiesPile, discardPile } = roomsStore[roomName]
-    const discardedPolicy = take(policiesPile, 1)[0]
+    const discardedPolicy = takeRight(policiesPile, 1)[0]
+    console.log(discardedPolicy)
```
Comment (Dammic) [inline utils/RoomsManager/policies.mjs]: :scissors:

File: events/SocketEvents.mjs (hunk 2 above)
Comment (polarny) [reply events/SocketEvents.mjs]: Done.

File: events/EnactPolicyEvents.mjs (hunk 3 above)
Comment (polarny) [reply events/EnactPolicyEvents.mjs]: Done.

File: src/utils/SocketHandler.js (hunk 5 above)
Comment (polarny) [reply src/utils/SocketHandler.js]: Done.

File: events/emits/superpowers.mjs (hunk 4 above)
Comment (polarny) [reply events/emits/superpowers.mjs]: Done.

File: utils/RoomsManager/policies.mjs (hunk 8 above)
Comment (polarny) [reply utils/RoomsManager/policies.mjs]: Done.

File: utils/RoomsManager/__tests__/voting.test.mjs (hunk 7 above)
Comment (polarny) [reply utils/RoomsManager/__tests__/voting.test.mjs]: Done, but I didn't see any point to using 'updateRoom'.

Comment (polarny) [reply utils/RoomsManager/__tests__/voting.test.mjs]: Done

Comment (polarny) [reply utils/RoomsManager/__tests__/voting.test.mjs]: Done

File: src/utils/SocketHandler.js [hunk 9]
```diff
@@ -324,6 +324,7 @@ export class SocketHandler extends React.PureComponent {
 
 const mapStateToProps = ({ user, room }) => {
     return {
+        room,
```
Comment (Dammic) [inline src/utils/SocketHandler.js]: You have the trackerPosition right below - you should use that prop instead of importing the whole room and then using this.props.room.
